### ISSUE TITLE
Long Press Detected as Released After Some Time

### ISSUE THREAD

**Issue by FXHLL** [antgon/pico-mpr121#2]
Dear Development Team,
While using the MPR121 library for Pico, we encountered an issue where long press operations are detected as released after about 30 to 40 cycles. Regardless of how long the press is held, the program incorrectly detects a release after a certain number of cycles.

**Comment by antgon** [comment]
This is expected behaviour: by default the touch sensor will release after some time even if touch persists, thus adjusting to environmental changes.

This behaviour can be adjusted to fit your needs. What I suggest you do is (i) read the MPR121 documentation, below, to understand how the MPR121 works, then (ii) tune the sensor accordingly; see the file `tune_sensor.c` in the examples folder in this library for ideas.

Useful NXP Application notes:
* [MPR121 Quick Start Guide (pdf)](https://www.nxp.com/docs/en/application-note/AN3944.pdf)
* [MPR121 Capacitance Sensing — Filtering and Timing (pdf)](https://www.nxp.com/docs/en/application-note/AN3890.pdf)
* [MPR121 Baseline System (pdf)](https://www.nxp.com/docs/en/application-note/AN3891.pdf)
* [MPR121 Capacitance Sensing Settings (pdf)](https://www.nxp.com/docs/en/application-note/AN3889.pdf)
* [MPR121 Jitter and False Touch Detection (pdf)](https://www.nxp.com/docs/en/application-note/AN3892.pdf)
